@startuml

title __SRC's Class Diagram__\n

    class DifficultySection {
        {static} + difficultyScene()
    }
  

    class GameSection {
        {static} + target : Circle
        {static} ~ INGAME_MENU_SIZE : int
        {static} + gameScene()
    }
  

    class LeaderboardsSection {
        {static} + leaderboardsScene()
    }
  

    class Lefreks {
        {static} ~ RESX : int
        {static} ~ RESY : int
        {static} + main()
        + start()
        + stop()
    }
  

    class MenuSection {
        {static} + menuScene()
    }
  

    class NumberHandler {
        ~ startCounting : TimerTask
        ~ timer : Timer
        - points : int
        - pointsText : StringProperty
        - startTimer : boolean
        - startedTimer : boolean
        {static} - targetDuration : int
        - targetDurationTime : int
        {static} - targetSize : int
        - timePassed : int
        - timePassedTemp : int
        - timerText : StringProperty
        + getPoints()
        + getPointsText()
        + getTargetDuration()
        + getTargetDurationTime()
        + getTargetSize()
        + getTimePassed()
        + getTimePassedTemp()
        + getTimerText()
        + isStartTimer()
        + isStartedTimer()
        + reset()
        + setPoints()
        + setStartTimer()
        + setStartedTimer()
        + setTargetDuration()
        + setTargetDurationTime()
        + setTargetSize()
        + setTimePassed()
        + setTimePassedTemp()
    }

  Lefreks o-- NumberHandler : numberHandler


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
